image: Visual Studio 2017
platform: Any CPU

environment:
  version: $(APPVEYOR_BUILD_VERSION)

configuration:
- Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%version%'
  package_version: '%version%'
  assembly_version: '%version%'
  file_version: '%version%'
  informational_version: '%version%'

before_build:
  - choco install opencover.portable
  - choco install codecov
  - dotnet restore

build:
  project: Elasticsearch.BulkAndSearch.sln

test_script:
  - OpenCover.Console.exe -oldstyle -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full Elasticsearch.BulkAndSearch.Tests\Elasticsearch.BulkAndSearch.Tests.csproj" -filter:"+[Elasticsearch.BulkAndSearch*]* -[Elasticsearch.BulkAndSearch.Tests*]*" -output:".\coverage.xml"
  - codecov -f .\coverage.xml -t %CODECOV_TOKEN%

after_test:
  - dotnet pack --configuration Release /p:Version=%version%

artifacts:
  - path: Elasticsearch.BulkAndSearch\bin\Release\netstandard2.0\Elasticsearch.BulkAndSearch.dll
    name: Elasticsearch.BulkAndSearch.dll
  - path: Elasticsearch.BulkAndSearch\bin\Release\Elasticsearch.BulkAndSearch.%version%.nupkg
    name: Elasticsearch.BulkAndSearch.%version%.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: csyDlyeSjDmdYAQ/PK0GYNZ4ofK/yC6vd5ZLPnG2TgujmrAW7fUiQxjDVOWD4XAX